ПРАКТИЧНА РОБОТА 1

---


Вступ до машинного навчання. Елементи лінійної алгебри.
>
Варіант №7
>
Мій githab:https://github.com/Uchiha-Ihor/Machine_learning

Завдання 1: Створіть одновимірний масив (вектор) зі сходячою послідовністю чисел, де кожне наступне число більше попереднього на 3, починаючи з 5, та виведіть його значення.

In [16]:
import numpy as np

start = 5

num_elements = 10

step = 3
vector = np.arange(start, start + step * num_elements, step)

print(vector)



[ 5  8 11 14 17 20 23 26 29 32]


Завдання 2: Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його добутками квадратів кожного числа та його подвійного значення, починаючи з 1, та виведіть його значення.

In [18]:
import numpy as np

rows, cols = 3, 3

matrix = np.zeros((rows, cols))

value = 1
for i in range(rows):
    for j in range(cols):
        matrix[i][j] = (value ** 2) * (2 * value)
        value += 1

print(matrix)

[[   2.   16.   54.]
 [ 128.  250.  432.]
 [ 686. 1024. 1458.]]


Завдання 3: Створіть масив розміром 10x10, заповніть його випадковими дійсними числами в діапазоні від -50 до 50 та виведіть його значення.

In [19]:
import numpy as np

rows, cols = 10, 10

low = -50
high = 50

matrix = np.random.uniform(low, high, (rows, cols))

print(matrix)

[[-2.46911502e+00  1.61532695e+01  2.00078226e+01  7.43399277e+00
  -3.20570716e+01 -3.10530814e+01  3.90593686e+01 -1.57835992e+00
  -4.30302688e+01  2.92996685e+01]
 [-2.12905603e+01 -2.30161869e+01 -4.06966220e+01  4.62137571e+01
  -2.50006361e+01  4.70816242e+01 -1.76223166e+01 -2.30915571e+01
  -4.63830106e+01 -2.36770919e+01]
 [ 4.19571469e+01 -4.15151573e+00  4.15628855e+01 -2.87461815e+01
   2.53871327e+01 -2.05552066e+01 -1.73001653e+01 -2.44818931e+01
  -1.81298112e+01 -1.51673373e+01]
 [ 2.71492512e+01  4.74236969e+01  2.37367820e+01 -4.74463054e+01
  -1.48844504e+01  2.77230307e+01 -6.55591634e+00 -1.18090635e+01
  -7.68268339e+00  2.94548463e+01]
 [ 2.39169561e+01 -1.05352246e+01  2.62754523e+01 -1.51964958e+01
   4.45236604e+01 -3.84090897e+01 -4.56141639e+01 -2.19606437e+01
   1.93583221e+01 -4.92302074e+01]
 [-5.27281158e+00  2.33125215e+01  2.49229705e+01  1.36547672e+01
  -4.42812050e+01  2.84573256e+01  3.69096089e+01  3.18303519e+01
   2.92358119e+01 -1.81667510e+01

Завдання 4: Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-рядок, що містить середнє значення елементів кожного стовпця матриці.

In [20]:
import numpy as np

rows, cols = 4, 4

low = 0
high = 1

matrix = np.random.uniform(low, high, (rows, cols))

mean_vector = np.mean(matrix, axis=0)

print("Матриця:")
print(matrix)
print("\nВектор-рядок з середніми значеннями стовпців:")
print(mean_vector)

Матриця:
[[0.07840317 0.88976095 0.57651744 0.05842402]
 [0.35813317 0.3101679  0.18173336 0.8550464 ]
 [0.95671434 0.29006476 0.70357522 0.79138081]
 [0.85939083 0.74953209 0.26155212 0.08290704]]

Вектор-рядок з середніми значеннями стовпців:
[0.56316038 0.55988143 0.43084453 0.44693957]


Завдання 5: Створіть два одновимірних масиви розміром 7, заповніть їх випадковими дійсними числами від -2.5 до 2.5 та виконайте на них поелементні операції додавання, віднімання та множення.

In [21]:
import numpy as np

size = 7

low = -2.5
high = 2.5

array1 = np.random.uniform(low, high, size)
array2 = np.random.uniform(low, high, size)

addition_result = array1 + array2
subtraction_result = array1 - array2
multiplication_result = array1 * array2

print("Масив 1:", array1)
print("Масив 2:", array2)
print("Результат додавання:", addition_result)
print("Результат віднімання:", subtraction_result)
print("Результат множення:", multiplication_result)

Масив 1: [-1.49524375 -2.1432511   0.58693508 -1.36028643 -2.38496979  0.22119543
 -1.90358248]
Масив 2: [ 1.61596579 -0.29560174 -1.86995172  0.74727539 -0.01917157  2.30904258
  1.77378466]
Результат додавання: [ 0.12072204 -2.43885285 -1.28301664 -0.61301104 -2.40414135  2.53023801
 -0.12979781]
Результат віднімання: [-3.11120955 -1.84764936  2.4568868  -2.10756182 -2.36579822 -2.08784716
 -3.67736714]
Результат множення: [-2.41626276  0.63354876 -1.09754026 -1.01650857  0.04572361  0.51074966
 -3.3765454 ]


Завдання 6: Створіть два вектори розміром 7, заповніть їх довільними цілими числами та знайдіть їх скалярний добуток.

In [22]:
import numpy as np

size = 7

vector1 = np.random.randint(1, 11, size)
vector2 = np.random.randint(1, 11, size)

dot_product = np.dot(vector1, vector2)

print("Вектор 1:", vector1)
print("Вектор 2:", vector2)
print("Скалярний добуток:", dot_product)

Вектор 1: [7 4 5 4 5 9 7]
Вектор 2: [ 7  5  3  4 10  6 10]
Скалярний добуток: 274


Завдання 7: Створіть дві матриці розміром 4x2 та 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [23]:
import numpy as np

rows1, cols1 = 4, 2
rows2, cols2 = 2, 2

low = 1
high = 10

matrix1 = np.random.randint(low, high + 1, (rows1, cols1))
matrix2 = np.random.randint(low, high + 1, (rows2, cols2))

result = np.dot(matrix1, matrix2)

print("Матриця 1:")
print(matrix1)
print("\nМатриця 2:")
print(matrix2)
print("\nРезультат перемноження:")
print(result)

Матриця 1:
[[ 3  4]
 [ 9  5]
 [ 1 10]
 [ 3  7]]

Матриця 2:
[[5 9]
 [1 2]]

Результат перемноження:
[[19 35]
 [50 91]
 [15 29]
 [22 41]]


Завдання 8: Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні від 1 до 12 та знайдіть її обернену матрицю

In [24]:
import numpy as np

rows, cols = 2, 2

low = 1
high = 12

matrix = np.random.randint(low, high + 1, (rows, cols))

print("Початкова матриця:")
print(matrix)

try:
    inverse_matrix = np.linalg.inv(matrix)
    print("\nОбернена матриця:")
    print(inverse_matrix)
except np.linalg.LinAlgError:
    print("\nОбернена матриця не існує, оскільки детермінант дорівнює 0.")

Початкова матриця:
[[1 7]
 [1 4]]

Обернена матриця:
[[-1.33333333  2.33333333]
 [ 0.33333333 -0.33333333]]


Завдання 9: Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 0 до 1 та транспонуйте її.

In [25]:
import numpy as np

rows, cols = 3, 3

low = 0
high = 1

matrix = np.random.randint(low, high + 1, (rows, cols))

print("Початкова матриця:")
print(matrix)

transposed_matrix = np.transpose(matrix)

print("\nТранспонована матриця:")
print(transposed_matrix)

Початкова матриця:
[[1 0 0]
 [1 1 0]
 [1 1 1]]

Транспонована матриця:
[[1 1 1]
 [0 1 1]
 [0 0 1]]


Завдання 10: Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть матрицю випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими дійсними числами від 0 до 1, і знайдіть суму додатних елементів отриманої матриці.

In [27]:
import numpy as np

matrix_rows, matrix_cols = 3, 4
vector_size = 4

low_matrix = 1
high_matrix = 10

low_vector = 0
high_vector = 1

matrix = np.random.randint(low_matrix, high_matrix + 1, (matrix_rows, matrix_cols))

vector = np.random.uniform(low_vector, high_vector, vector_size)

print("Матриця:")
print(matrix)
print("\nВектор:")
print(vector)

positive_elements_sum = np.sum(matrix[matrix > 0])

print("\nСума додатних елементів матриці:", positive_elements_sum)

Матриця:
[[10  2  2  5]
 [ 6  9  3  8]
 [10  3  7  5]]

Вектор:
[0.96236322 0.38475417 0.65207533 0.64287674]

Сума додатних елементів матриці: 70


Завдання 11: Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.

In [28]:
import numpy as np

matrix_rows, matrix_cols = 2, 3
vector_size = 3

low_matrix = 0
high_matrix = 1

low_vector = 1
high_vector = 10

matrix = np.random.uniform(low_matrix, high_matrix, (matrix_rows, matrix_cols))

vector = np.random.randint(low_vector, high_vector + 1, vector_size)

print("Матриця:")
print(matrix)
print("\nВектор:")
print(vector)

result = np.dot(matrix, vector)

print("\nДобуток матриці на вектор:")
print(result)

Матриця:
[[0.50143265 0.32048819 0.09659449]
 [0.35623317 0.1146491  0.25394299]]

Вектор:
[9 6 4]

Добуток матриці на вектор:
[6.82220095 4.90976509]


Завдання 12: Створіть дві матриці розміром 8x8, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть різницю елементів першої матриці.

In [29]:
import numpy as np

rows, cols = 8, 8

low = 1
high = 10

matrix1 = np.random.randint(low, high + 1, (rows, cols))
matrix2 = np.random.randint(low, high + 1, (rows, cols))

difference_matrix = matrix1 - matrix2

print("Матриця 1:")
print(matrix1)
print("\nМатриця 2:")
print(matrix2)
print("\nРізниця між елементами першої матриці:")
print(difference_matrix)

Матриця 1:
[[ 9  6  9  5  3  5  2  8]
 [ 7  2  3  7  2  3 10  9]
 [ 7  4  3  9  4  3  8  3]
 [ 8  4  1  3  5  5 10 10]
 [ 5  5  5  5  4  4  4  2]
 [ 4  3  3 10  5  3  6  8]
 [ 5 10  2  9  9  4  3  2]
 [ 5  8  2  5  9  8  6  3]]

Матриця 2:
[[10  4  4  6  4 10  4  3]
 [ 7  4  4  8  4  1  1  7]
 [ 4  7  6  1  2  3  1  6]
 [ 9 10  3  9  7  7  4  5]
 [ 1  2  8  5  9  8  7  9]
 [ 6  5  5  4  9 10  3  3]
 [10  4  2  1  3  7  9  4]
 [ 8  1 10  8  1 10 10  3]]

Різниця між елементами першої матриці:
[[-1  2  5 -1 -1 -5 -2  5]
 [ 0 -2 -1 -1 -2  2  9  2]
 [ 3 -3 -3  8  2  0  7 -3]
 [-1 -6 -2 -6 -2 -2  6  5]
 [ 4  3 -3  0 -5 -4 -3 -7]
 [-2 -2 -2  6 -4 -7  3  5]
 [-5  6  0  8  6 -3 -6 -2]
 [-3  7 -8 -3  8 -2 -4  0]]


Завдання 13: Створіть дві матриці розміром 8x8, заповніть їх випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть різницю їх елементів.

In [30]:
import numpy as np

rows, cols = 8, 8

low = -1
high = 1

matrix1 = np.random.uniform(low, high, (rows, cols))
matrix2 = np.random.uniform(low, high, (rows, cols))

difference_matrix = matrix1 - matrix2

print("Матриця 1:")
print(matrix1)
print("\nМатриця 2:")
print(matrix2)
print("\nРізниця між елементами матриць:")
print(difference_matrix)

Матриця 1:
[[-0.99443604  0.51295703  0.33716555 -0.44744434 -0.44889902 -0.33808136
   0.99375953 -0.97361285]
 [ 0.82323912  0.03824992 -0.13938629  0.2303346  -0.78171632  0.51274162
  -0.20391031  0.36668849]
 [-0.39292595 -0.89802154  0.34918511 -0.1423216  -0.22957657 -0.07810504
  -0.15941697 -0.85429584]
 [-0.88513538  0.21116389 -0.65540099  0.797998    0.63138282  0.25645444
   0.9260996  -0.66189597]
 [ 0.58261519  0.18623029 -0.00886103  0.13446422  0.15544838  0.91957529
   0.88284258 -0.95233776]
 [ 0.79053414  0.25932619 -0.47611402 -0.59195004 -0.51045707 -0.9537696
   0.83802321 -0.42115983]
 [ 0.7281969   0.23783703 -0.81789652  0.30523402  0.00917619  0.87510124
  -0.02814343 -0.48125746]
 [ 0.45751924 -0.40877384  0.5700186  -0.5825954  -0.66209865 -0.77169895
   0.67674709  0.75166757]]

Матриця 2:
[[-0.01229106 -0.43489019 -0.13592387 -0.70450721  0.8927684   0.27789964
   0.40000313  0.3681676 ]
 [-0.58348386 -0.8088872   0.20643205  0.12556342  0.49594681 -0.731

Завдання 14: Створіть матрицю розміром 5x5, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть середнє арифметичне значення елементів матриці.

In [31]:
import numpy as np

rows, cols = 5, 5

low = 0
high = 1

matrix = np.random.uniform(low, high, (rows, cols))

mean_value = np.mean(matrix)

print("Матриця:")
print(matrix)
print("\nСереднє арифметичне значення елементів матриці:", mean_value)

Матриця:
[[0.594654   0.4837643  0.41901712 0.8170724  0.58243781]
 [0.06479827 0.91212273 0.33223419 0.53323407 0.89949546]
 [0.2984189  0.71139347 0.46709474 0.93015683 0.85380466]
 [0.31098088 0.46722773 0.66886973 0.95977735 0.26750893]
 [0.74184226 0.23165774 0.39706397 0.13487293 0.06545549]]

Середнє арифметичне значення елементів матриці: 0.5257982392473849


Завдання 15: Створіть матрицю розміром 9x9, заповніть її випадковими дійсними числами в діапазоні від -0.5 до 0.5 та знайдіть вектор-стовпчик, що містить найбільше за модулем значення елементу у кожному рядку матриці.

In [32]:
import numpy as np

rows, cols = 9, 9

low = -0.5
high = 0.5

matrix = np.random.uniform(low, high, (rows, cols))

max_abs_values_vector = np.argmax(np.abs(matrix), axis=1)

print("Матриця:")
print(matrix)
print("\nВектор-стовпчик з найбільшими за модулем значеннями:")
print(max_abs_values_vector)

Матриця:
[[ 0.21697743 -0.01632581  0.31650113  0.40890857 -0.03413892 -0.07055369
   0.30775075 -0.02949591 -0.16300068]
 [ 0.28749639  0.36124507 -0.05914124 -0.05504292  0.45850091 -0.29381949
  -0.24353753 -0.28248261  0.07095797]
 [-0.31641594  0.48759428  0.41165061 -0.33087562 -0.46770237 -0.16037512
  -0.47719765  0.01276704 -0.10116944]
 [-0.49209806 -0.3236956  -0.43338383 -0.37906933 -0.26780699 -0.20366139
  -0.29460232  0.13078978 -0.43409903]
 [ 0.42578167  0.24430242 -0.37632888 -0.30332768 -0.34017892 -0.4890975
   0.17866466 -0.26567258 -0.3391108 ]
 [ 0.47830086 -0.48330745 -0.37797718  0.32210159 -0.17128449  0.38401656
  -0.21126766 -0.37312127  0.15839991]
 [-0.03686145 -0.2903052   0.31522141 -0.29749926  0.10577535 -0.11086322
   0.29416218  0.43590266 -0.39176357]
 [-0.41590792 -0.36137434  0.01873531 -0.24192914 -0.4193273  -0.32019685
  -0.38356388  0.08442863 -0.10877961]
 [ 0.36918372  0.06651817  0.46241719 -0.30334298 -0.35839432  0.49756699
   0.009732   